// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvpnweczvrhijljvrips.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52cG53ZWN6dnJoaWpsanZyaXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5Mjk4NDcsImV4cCI6MjA3MTUwNTg0N30.XdiT1w0c89UBEHf_p7jWZYegqONtmhBvCKGUHnVsdY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});